apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-logs-pvc
  namespace: confluent-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage

